const mongoose = require('mongoose');

const ExpenseSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true }, // The ID generated by the App
  title: { type: String },
  amount: { type: Number },
  category: { type: String },
  timestamp: { type: Number }
});

module.exports = mongoose.model('Expense', ExpenseSchema);