const mongoose = require('mongoose');

const LedgerSchema = new mongoose.Schema({
  // FIX: Change the type from ObjectId to String to accept the UUIDs generated by the mobile app.
  tailor_id: { type: String, required: true }, 
  
  description: String,
  amount: Number,
  type: { type: String, enum: ['DEBIT', 'CREDIT'] },
  timestamp: { type: Number, default: Date.now }
});

module.exports = mongoose.model('Ledger', LedgerSchema);