// const mongoose = require('mongoose');

// const LedgerSchema = new mongoose.Schema({
//   // FIX: Change the type from ObjectId to String to accept the UUIDs generated by the mobile app.
//   tailor_id: { type: String, required: true }, 
//   
//   description: String,
//   amount: Number,
//   type: { type: String, enum: ['DEBIT', 'CREDIT'] },
//   timestamp: { type: Number, default: Date.now }
// });

// module.exports = mongoose.model('Ledger', LedgerSchema);


const mongoose = require('mongoose');

const LedgerSchema = new mongoose.Schema({
  // 1. Explicitly define _id as a String to accept your mobile app's UUIDs
  _id: { type: String, required: true }, 

  // This links to the Tailor's ID (which is also a String now)
  tailor_id: { type: String, required: true }, 
  
  description: String,
  amount: Number,
  type: { type: String, enum: ['DEBIT', 'CREDIT'] },
  timestamp: { type: Number, default: Date.now }
}, { 
  // 2. Disable auto-id generation (since we provide it)
  _id: false,
  timestamps: true, // Optional: Adds createdAt/updatedAt
  
  // 3. Helper to convert _id back to 'id' when sending data back to the app
  toJSON: {
    virtuals: true,
    transform: (doc, ret) => {
      ret.id = ret._id;
      delete ret._id;
      delete ret.__v;
    }
  }
});

module.exports = mongoose.model('Ledger', LedgerSchema);